#!/usr/bin/env python3
"""
Collect paper-table reproduction artifacts for the nuScenes-only project.

This script is intentionally lightweight: it does not train a model and does not
run inference. It collects existing artifacts from the root AutoVLA repository and
exports side-by-side Markdown/JSON tables. Heavy tables such as runtime profiling
and full nuScenes evaluation should be generated by their dedicated SLURM scripts
first, then this script collects the outputs.

The function names follow the final-project expectation: one function per paper
table. Tables outside the nuScenes-only scope are still represented with a clear
scope note instead of silently disappearing.
"""

from __future__ import annotations

import json
import math
import re
from pathlib import Path


REPRO_DIR = Path(__file__).resolve().parent
ROOT_DIR = REPRO_DIR.parent
OUT_DIR = REPRO_DIR / "evaluation_results"


def fmt(value, digits=4):
    if value is None:
        return "TBD"
    if isinstance(value, float):
        if math.isnan(value) or math.isinf(value):
            return "nan"
        return f"{value:.{digits}f}"
    return str(value)


def load_json(path: Path):
    if not path.exists():
        return None
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def markdown_table(headers, rows):
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join(["---"] * len(headers)) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(str(cell) for cell in row) + " |")
    return "\n".join(lines)


def avg3(a, b, c):
    if a is None or b is None or c is None:
        return None
    return (a + b + c) / 3.0


def parse_planning_table(path: Path):
    if not path.exists():
        return {}
    text = path.read_text(encoding="utf-8", errors="ignore")
    rows = re.findall(
        r"\|\s*(obj_col|obj_box_col|L2)\s*\|\s*"
        r"([0-9.]+|nan)\s*\|\s*([0-9.]+|nan)\s*\|\s*([0-9.]+|nan)\s*\|\s*"
        r"([0-9.]+|nan)\s*\|\s*([0-9.]+|nan)\s*\|\s*([0-9.]+|nan)\s*\|",
        text,
    )
    if len(rows) < 6:
        return {}

    final_rows = rows[-6:]
    horizons = ["0.5s", "1.0s", "1.5s", "2.0s", "2.5s", "3.0s"]
    protocols = {"stp3": {}, "uniad": {}}
    for protocol, protocol_rows in [("stp3", final_rows[:3]), ("uniad", final_rows[3:])]:
        for row in protocol_rows:
            metric = row[0]
            protocols[protocol][metric] = {
                horizon: float(value) if value != "nan" else float("nan")
                for horizon, value in zip(horizons, row[1:])
            }
    return protocols


def load_planning_metrics():
    """Load Table S2 metrics from the most stable available local artifact."""
    candidates = [
        ROOT_DIR / "logs" / "12_evaluate.out",
        ROOT_DIR / "planning_table.txt",
        ROOT_DIR / "evaluation_results_20260501_222241" / "planning_table.txt",
    ]
    for path in candidates:
        local = parse_planning_table(path)
        if local:
            return local, path
    return {}, None


def count_json_files(path: Path) -> int:
    return len(list(path.glob("*.json"))) if path.exists() else 0


def unsupported_table(table_id, title, reason):
    return {
        "table_id": table_id,
        "title": title,
        "status": "not_reproduced_in_nuscenes_only_scope",
        "reason": reason,
        "rows": [],
    }


def reproduce_table_1():
    return unsupported_table(
        "Table 1",
        "NAVSIM planning benchmark",
        "Table 1 is a nuPlan/NAVSIM benchmark. This repository currently focuses on nuScenes-only reproduction.",
    )


def reproduce_table_2():
    paper = {
        "fast_min_s": 0.997,
        "fast_max_s": 1.116,
        "fast_avg_s": 1.072,
        "slow_min_s": 7.607,
        "slow_max_s": 13.706,
        "slow_avg_s": 10.518,
        "slow_fast_ratio": 9.8,
    }
    result_path = OUT_DIR / "table_2_runtime.json"
    local = load_json(result_path)
    status = "artifact_found" if local else "missing_runtime_artifact"
    return {
        "table_id": "Table 2",
        "title": "Runtime analysis: fast vs slow thinking",
        "status": status,
        "paper": paper,
        "local": local,
        "artifact": str(result_path.relative_to(REPRO_DIR)),
        "how_to_generate": "sbatch slurm_scripts/14_reproduce_table_2.slurm",
    }


def reproduce_table_3():
    return unsupported_table(
        "Table 3",
        "Bench2Drive / CARLA closed-loop benchmark",
        "Table 3 requires CARLA/Bench2Drive closed-loop evaluation, outside the nuScenes-only project scope.",
    )


def reproduce_table_4():
    paper = {
        "256": {"rt1_ade": 0.1440, "rt1_fde": 0.2942, "fast_ade": 0.1708, "fast_fde": 0.2137, "kdisk_ade": 0.0687, "kdisk_fde": 0.1034, "mc": 86.47, "cu": 100.0},
        "1024": {"rt1_ade": 0.1052, "rt1_fde": 0.1883, "fast_ade": 0.0522, "fast_fde": 0.0588, "kdisk_ade": 0.0253, "kdisk_fde": 0.0282, "mc": 97.41, "cu": 100.0},
        "2048": {"rt1_ade": 0.1014, "rt1_fde": 0.1775, "fast_ade": 0.0281, "fast_fde": 0.0309, "kdisk_ade": 0.0182, "kdisk_fde": 0.0203, "mc": 99.42, "cu": 100.0},
        "4096": {"rt1_ade": 0.1001, "rt1_fde": 0.1739, "fast_ade": 0.0149, "fast_fde": 0.0161, "kdisk_ade": 0.0141, "kdisk_fde": 0.0155, "mc": 100.0, "cu": 91.46},
    }
    local = load_json(ROOT_DIR / "evaluation_results_data_scaling" / "table4_kdisk_metrics.json") or {}
    return {
        "table_id": "Table 4",
        "title": "Action tokenization accuracy",
        "status": "partial_kdisk_only",
        "paper": paper,
        "local_kdisk": local,
        "note": "Local artifacts currently cover K-disk metrics only for available K values; RT-1/FAST baselines are not reproduced yet.",
    }


def reproduce_table_5():
    return unsupported_table(
        "Table 5",
        "Influence of physical action tokenization",
        "Requires training/evaluating text-waypoint and physical-action variants. Not available yet in the nuScenes-only artifacts.",
    )


def reproduce_table_6():
    return unsupported_table(
        "Table 6",
        "Tokenization methods on NAVSIM",
        "Requires NAVSIM/nuPlan evaluation for FAST and K-disk. This is outside the current nuScenes-only scope.",
    )


def reproduce_table_s2():
    paper = {
        "action_only": {
            "stp3_l2_1s": 0.22, "stp3_l2_2s": 0.39, "stp3_l2_3s": 0.61, "stp3_avg_l2": 0.41,
            "stp3_coll_1s": 0.10, "stp3_coll_2s": 0.17, "stp3_coll_3s": 0.28, "stp3_avg_coll": 0.18,
            "uniad_l2_1s": 0.29, "uniad_l2_2s": 0.67, "uniad_l2_3s": 1.17, "uniad_avg_l2": 0.71,
            "uniad_coll_1s": 0.15, "uniad_coll_2s": 0.34, "uniad_coll_3s": 0.56, "uniad_avg_coll": 0.35,
        },
        "with_cot": {
            "stp3_l2_1s": 0.21, "stp3_l2_2s": 0.38, "stp3_l2_3s": 0.60, "stp3_avg_l2": 0.40,
            "stp3_coll_1s": 0.13, "stp3_coll_2s": 0.18, "stp3_coll_3s": 0.28, "stp3_avg_coll": 0.20,
            "uniad_l2_1s": 0.28, "uniad_l2_2s": 0.66, "uniad_l2_3s": 1.16, "uniad_avg_l2": 0.70,
            "uniad_coll_1s": 0.14, "uniad_coll_2s": 0.25, "uniad_coll_3s": 0.53, "uniad_avg_coll": 0.31,
        },
    }
    local, artifact_path = load_planning_metrics()
    return {
        "table_id": "Table S2",
        "title": "nuScenes planning benchmark",
        "status": "local_observed_gap",
        "paper": paper,
        "local": local,
        "artifact": str(artifact_path.relative_to(ROOT_DIR)) if artifact_path else None,
        "note": "Local values are parsed from the available planning metric artifact and should be treated as observed gap until metric alignment and action-token fallback audit are complete.",
        "how_to_generate": "sbatch slurm_scripts/13_reproduce_table_s2.slurm",
    }


def dataset_context():
    train = count_json_files(ROOT_DIR / "data" / "nuscenes_processed" / "train")
    val = count_json_files(ROOT_DIR / "data" / "nuscenes_processed" / "val")
    return {
        "train_samples": train,
        "val_samples": val,
        "total_samples": train + val,
        "scope": "nuScenes-only",
    }


def build_markdown(results):
    lines = [
        "# Paper Table Reproduction Status - nuScenes Only",
        "",
        "This file is generated by `reproduce_paper_tables_nuscenes.py`.",
        "It prioritizes the original paper tables and shows which ones are reproduced, partially reproduced, or out of scope for the current nuScenes-only project.",
        "",
        "## Dataset Context",
        "",
        markdown_table(
            ["Split", "Samples"],
            [
                ["Train", results["dataset_context"]["train_samples"]],
                ["Validation", results["dataset_context"]["val_samples"]],
                ["Total", results["dataset_context"]["total_samples"]],
            ],
        ),
        "",
    ]

    for key in ["table_1", "table_2", "table_3", "table_4", "table_5", "table_6", "table_s2"]:
        table = results[key]
        lines += [f"## {table['table_id']}: {table['title']}", "", f"Status: `{table['status']}`", ""]
        if table["table_id"] == "Table 2":
            local_summary = (table.get("local") or {}).get("summary", {})
            local_fast = local_summary.get("fast_thinking", {})
            local_slow = local_summary.get("slow_thinking", {})
            local_ratio = local_summary.get("ratio", {})
            lines += [
                markdown_table(
                    ["Mode", "Paper min", "Paper max", "Paper avg", "Local min", "Local max", "Local avg", "Local ratio"],
                    [
                        [
                            "Fast",
                            table["paper"]["fast_min_s"],
                            table["paper"]["fast_max_s"],
                            table["paper"]["fast_avg_s"],
                            fmt(local_fast.get("min"), 3),
                            fmt(local_fast.get("max"), 3),
                            fmt(local_fast.get("mean"), 3),
                            "1.0x" if local_fast else "TBD",
                        ],
                        [
                            "Slow",
                            table["paper"]["slow_min_s"],
                            table["paper"]["slow_max_s"],
                            table["paper"]["slow_avg_s"],
                            fmt(local_slow.get("min"), 3),
                            fmt(local_slow.get("max"), 3),
                            fmt(local_slow.get("mean"), 3),
                            f"{local_ratio.get('mean'):.1f}x" if local_ratio.get("mean") is not None else "TBD",
                        ],
                    ],
                ),
                "",
                f"Local artifact: `{table['artifact']}`",
                "",
                f"Generate with: `{table['how_to_generate']}`",
                "",
            ]
        elif table["table_id"] == "Table 4":
            rows = []
            for k in ["256", "1024", "2048", "4096"]:
                local = table["local_kdisk"].get(k, {})
                rows.append(
                    [
                        k,
                        table["paper"][k]["kdisk_ade"],
                        fmt(local.get("ADE")),
                        table["paper"][k]["kdisk_fde"],
                        fmt(local.get("FDE")),
                        table["paper"][k]["mc"],
                        fmt(local.get("MC"), 2),
                        table["paper"][k]["cu"],
                        fmt(local.get("CU"), 2),
                    ]
                )
            lines += [
                markdown_table(
                    ["K", "Paper ADE", "Local ADE", "Paper FDE", "Local FDE", "Paper MC", "Local MC", "Paper CU", "Local CU"],
                    rows,
                ),
                "",
                table["note"],
                "",
            ]
        elif table["table_id"] == "Table S2":
            local = table.get("local", {})
            if local:
                paper_headers = [
                    "Method",
                    "ST-P3 L2@1s", "ST-P3 L2@2s", "ST-P3 L2@3s", "ST-P3 Avg L2",
                    "ST-P3 Coll@1s", "ST-P3 Coll@2s", "ST-P3 Coll@3s", "ST-P3 Avg Coll",
                    "UniAD L2@1s", "UniAD L2@2s", "UniAD L2@3s", "UniAD Avg L2",
                    "UniAD Coll@1s", "UniAD Coll@2s", "UniAD Coll@3s", "UniAD Avg Coll",
                ]

                def paper_row(label, key):
                    p = table["paper"][key]
                    return [
                        label,
                        p["stp3_l2_1s"], p["stp3_l2_2s"], p["stp3_l2_3s"], p["stp3_avg_l2"],
                        p["stp3_coll_1s"], p["stp3_coll_2s"], p["stp3_coll_3s"], p["stp3_avg_coll"],
                        p["uniad_l2_1s"], p["uniad_l2_2s"], p["uniad_l2_3s"], p["uniad_avg_l2"],
                        p["uniad_coll_1s"], p["uniad_coll_2s"], p["uniad_coll_3s"], p["uniad_avg_coll"],
                    ]

                stp3_l2 = local["stp3"]["L2"]
                stp3_col = local["stp3"]["obj_col"]
                uniad_l2 = local["uniad"]["L2"]
                uniad_col = local["uniad"]["obj_col"]
                rows = [
                    paper_row("AutoVLA action-only (paper)", "action_only"),
                    paper_row("AutoVLA w/ CoT (paper)", "with_cot"),
                    [
                        "AutoVLA nuScenes-only reproduction (ours)",
                        fmt(stp3_l2["1.0s"]), fmt(stp3_l2["2.0s"]), fmt(stp3_l2["3.0s"]),
                        fmt(avg3(stp3_l2["1.0s"], stp3_l2["2.0s"], stp3_l2["3.0s"])),
                        fmt(stp3_col["1.0s"]), fmt(stp3_col["2.0s"]), fmt(stp3_col["3.0s"]),
                        fmt(avg3(stp3_col["1.0s"], stp3_col["2.0s"], stp3_col["3.0s"])),
                        fmt(uniad_l2["1.0s"]), fmt(uniad_l2["2.0s"]), fmt(uniad_l2["3.0s"]),
                        fmt(avg3(uniad_l2["1.0s"], uniad_l2["2.0s"], uniad_l2["3.0s"])),
                        fmt(uniad_col["1.0s"]), fmt(uniad_col["2.0s"]), fmt(uniad_col["3.0s"]),
                        fmt(avg3(uniad_col["1.0s"], uniad_col["2.0s"], uniad_col["3.0s"])),
                    ],
                ]
                lines += [
                    markdown_table(paper_headers, rows),
                    "",
                    f"Local artifact: `{table['artifact']}`",
                    "",
                    table["note"],
                    "",
                    "Collision naming note: the local evaluator reports `obj_col` and `obj_box_col`; the paper reports collision rate. Keep them side by side until metric alignment is finalized.",
                    "",
                    f"Generate with: `{table['how_to_generate']}`",
                    "",
                ]
            else:
                lines += ["Local planning metrics were not found.", ""]
        else:
            lines += [table["reason"], ""]
    return "\n".join(lines)


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    results = {
        "dataset_context": dataset_context(),
        "table_1": reproduce_table_1(),
        "table_2": reproduce_table_2(),
        "table_3": reproduce_table_3(),
        "table_4": reproduce_table_4(),
        "table_5": reproduce_table_5(),
        "table_6": reproduce_table_6(),
        "table_s2": reproduce_table_s2(),
    }
    json_path = OUT_DIR / "paper_tables_nuscenes.json"
    md_path = OUT_DIR / "paper_tables_nuscenes.md"
    json_path.write_text(json.dumps(results, indent=2), encoding="utf-8")
    md_path.write_text(build_markdown(results), encoding="utf-8")
    print(f"Wrote {json_path}")
    print(f"Wrote {md_path}")


if __name__ == "__main__":
    main()
